#!/bin/bash -ex

# ARG_TAG:ES_PLUGINS
ES_PLUGINS_TAGS=(
  "s3:repository-s3"
  "gcs:repository-gcs"
)

for ES_PLUGINS in "${ES_PLUGINS_TAGS[@]}"; do
  if [[ $ES_PLUGINS =~ ":" ]]; then
    ARG_TAG="${ES_PLUGINS%%:*}"
    ES_PLUGINS="${ES_PLUGINS##*:}"
  else
    ARG_TAG="${ES_PLUGINS// /-}"
  fi
  FULL_IMAGE_NAME="${DOCKER_REPO?}:${DOCKER_TAG?}-${ARG_TAG?}"
  echo docker build --build-arg ES_PLUGINS="${ES_PLUGINS}" -f "${DOCKERFILE_PATH}" -t "${FULL_IMAGE_NAME}" ".${BUILD_PATH}"
  echo docker push "${FULL_IMAGE_NAME}"
done
